### ISSUE TITLE
LLVM tarball 404

### ISSUE THREAD

**Issue by ransomts** [StanfordLegion/task-bench#50]
Hi I'm trying to build this on my cluster and the llvm-3.8.1 tarball is failing to download from http://sapling.stanford.edu/~eslaught/llvm. Since this is hosted by Stanford I thought I'd let you know.

**Comment by elliottslaughter** [comment]
This is my fault. I'll put it back soon. In the mean time the original download at llvm.org is probably up.

**Comment by elliottslaughter** [comment]
The mirror should be back up now. Please try again.

**Comment by elliottslaughter** [comment]
Modern versions of Regent don't use the mirror anymore, making this a non-issue (unless GitHub goes down).
