### ISSUE TITLE
Move CI to Github Actions

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/task-bench#70]
Rationale is similar to https://github.com/terralang/terra/issues/355 . Rather than putting up with the migration and then subsequent limits, probably better to move to Github Actions, which is more performant anyway.

**Comment by lightsighter** [comment]
You're talking about just replacing the Travis CI right, not getting rid of our gitlab based CI?

**Comment by lightsighter** [comment]
Oops, thought this was Legion, should have paid more attention.

**Comment by elliottslaughter** [comment]
Right, this issue is for Task Bench, though we will have a similar (though more limited issue) with Legion. I will post a separate issue for that.

**Comment by elliottslaughter** [comment]
We did this a while ago.
