### ISSUE TITLE
Build fails on Ubuntu 18

### ISSUE THREAD

**Issue by gonidelis** [StanfordLegion/task-bench#72]
I am following the installation directions given in README and I get the following log when doing `./build_all.sh`.

```
make: Entering directory '/home/john/Desktop/hpx/thesis/task-bench/core'
rm -f core.o core_c.o core_kernel.o timer.o core_random.o siphash.o libcore.a libcore.so
make: Leaving directory '/home/john/Desktop/hpx/thesis/task-bench/core'
make: Entering directory '/home/john/Desktop/hpx/thesis/task-bench/core'
g++  -std=c++11 -fPIC -O3 -mavx -c -o core.o core.cc
g++  -std=c++11 -fPIC -O3 -mavx -c -o core_c.o core_c.cc
g++  -std=c++11 -fPIC -O3 -mavx -c -o core_kernel.o core_kernel.cc
g++  -std=c++11 -fPIC -O3 -mavx -c -o timer.o timer.cc
cc  -std=c11 -fPIC -O3 -mavx -c -o core_random.o core_random.c
cc  -std=c11 -fPIC -O3 -mavx -c -o siphash.o siphash.c
ln -sf libcore.a libcore_s.a
core.cc: In member function ‘void App::display() const’:
core.cc:1006:32: warning: too many arguments for format [-Wformat-extra-args]
                t, offset, width);
                                ^
core.cc:1021:44: warning: too many arguments for format [-Wformat-extra-args]
                  t, last_offset, last_width);
                                            ^
rm -f libcore.a
ar rc libcore.a core.o core_c.o core_kernel.o timer.o core_random.o siphash.o
rm -f libcore.so
g++  -shared -L. -Wl,--whole-archive -lcore -Wl,--no-whole-archive -o libcore.so.0
mv libcore.so.0 libcore.so
make: Leaving directory '/home/john/Desktop/hpx/thesis/task-bench/core'
make: Entering directory '/home/john/Desktop/hpx/thesis/task-bench/kernel_bench'
rm -f *.o
rm -f main
make: Leaving directory '/home/john/Desktop/hpx/thesis/task-bench/kernel_bench'
make: Entering directory '/home/john/Desktop/hpx/thesis/task-bench/kernel_bench'
g++ -c -std=c++11 -Wall -O3  -I../core  main.cc
g++ main.o -L../core -lcore_s  -std=c++11 -Wall -lpthread -O3  -o main 
make: Leaving directory '/home/john/Desktop/hpx/thesis/task-bench/kernel_bench'
make: Entering directory '/home/john/Desktop/hpx/thesis/task-bench/legion'
Makefile:53: /home/john/Desktop/hpx/thesis/task-bench/deps/legion/runtime/runtime.mk: No such file or directory
make: *** No rule to make target '/home/john/Desktop/hpx/thesis/task-bench/deps/legion/runtime/runtime.mk'.  Stop.
make: Leaving directory '/home/john/Desktop/hpx/thesis/task-bench/legion'
```

I have seen that your current master fails on Travis CI too with the same error status. Any pruposed workarounds?

**Comment by eddy16112** [comment]
The error is because the makefile can not find the directory of Legion, can you check if 
`export LG_RT_DIR=/home/john/Desktop/hpx/thesis/task-bench/deps/legion/runtime`
has been added to deps/env.sh?

**Comment by gonidelis** [comment]
@eddy16112 Yup, it has been added. I don't if that's related at all with the `DEFAULT_FEATURES=0 USE_LEGION=1 ./get_deps.sh
` part where I get:

```
Cloning into '/home/john/Desktop/hpx/thesis/task-bench/deps/legion'...
remote: Enumerating objects: 13032, done.
remote: Counting objects: 100% (13032/13032), done.
remote: Compressing objects: 100% (1916/1916), done.
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Comment by eddy16112** [comment]
> @eddy16112 Yup, it has been added. I don't know if that's related at all with the `DEFAULT_FEATURES=0 USE_LEGION=1 ./get_deps.sh` part where I get:
> 
> ```
> Cloning into '/home/john/Desktop/hpx/thesis/task-bench/deps/legion'...
> remote: Enumerating objects: 13032, done.
> remote: Counting objects: 100% (13032/13032), done.
> remote: Compressing objects: 100% (1916/1916), done.
> error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> ```

Looks like you did not clone the legion successfully, Please re-run the get_deps.sh or clone the legion manually
https://github.com/StanfordLegion/task-bench/blob/master/get_deps.sh#L136

**Comment by gonidelis** [comment]
@eddy16112 Weird... seems like deleting `/deps` dir and running `get_deps.sh` from scratch tackles this problem (the build still fails later on though).

**Comment by elliottslaughter** [comment]
@gonidelis is the issue resolved now?

We track so many systems that it's hard to keep 100% of the systems building at all times, but in general most things should work, and we do test 18.04 on our CI.

**Comment by gonidelis** [comment]
@elliottslaughter I totally get it. As I mentioned, the issue is resolved by deleting the `/deps` dir. Please feel free to close it and thanks a lot for the immediate response ;)
